name: Publish staging image
on:
  push:
    branches:
      - master
    tags:
      - '!**'
  workflow_dispatch:
jobs:
  build-push:
    environment: staging
    runs-on:
      group: self-hosted
    if: contains(github.event.head_commit.message, 'Back to development:') == false && contains(github.event.head_commit.message, 'Preparing release') == false
    steps:
      - name: Build push and notify
        uses: IMIO/gha/build-push-notify@v2.0
        with:
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ vars.IMAGE_NAME }}:staging
            ${{ secrets.HARBOR_URL }}/${{ vars.IMAGE_NAME }}:staging-${{ github.run_number }}
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.DOCS_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCS_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DOCS_MATTERMOST_WEBHOOK_URL }}
